apiVersion: v1
kind: ServiceAccount
metadata:
  name: medi-check-backend
  annotations:
    iam.gke.io/gcp-service-account: medi-check-cloudsql@medi-check-backend.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: medi-check-migrate
  annotations:
    iam.gke.io/gcp-service-account: medi-check-cloudsql@medi-check-backend.iam.gserviceaccount.com
