"""create init table

Revision ID: 7d1c6f60dc2c
Revises: 
Create Date: 2026-04-09 04:01:39.723686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d1c6f60dc2c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('birth_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INVITED', 'DISABLED', name='userstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('patients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('linked_user_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('birth_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['linked_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('linked_user_id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_id', sa.Uuid(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_id')
    )
    op.create_table('care_invitations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inviter_user_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.Column('invitee_email', sa.String(length=255), nullable=False),
    sa.Column('invitee_user_id', sa.Uuid(), nullable=True),
    sa.Column('invitation_type', sa.Enum('INVITE_PATIENT', 'INVITE_CAREGIVER', name='invitationtype'), nullable=False),
    sa.Column('permission_level', sa.Enum('READ', 'WRITE', 'ADMIN', name='permissionlevel'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'REVOKED', name='invitationstatus'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('declined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invitee_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inviter_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_invitations_invitee_email'), 'care_invitations', ['invitee_email'], unique=False)
    op.create_table('medications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('dosage_form', sa.Enum('Tablet', 'Capsule', 'Softgel', 'Liquid', 'Powder', 'Pill', 'Spray', name='dosageform'), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('care_relationships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('caregiver_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('invitation_id', sa.Uuid(), nullable=True),
    sa.Column('permission_level', sa.Enum('READ', 'WRITE', 'ADMIN', name='permissionlevel'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', name='relationshipstatus'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invitation_id'], ['care_invitations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('caregiver_user_id', 'patient_id', name='uq_caregiver_patient')
    )
    op.create_table('schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('medication_id', sa.Uuid(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('time_slots', sa.JSON(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('dose_unit', sa.Enum('Mg', 'Ml', 'Tablet', 'Capsule', 'Package', 'Drop', name='dosageunit'), nullable=True),
    sa.Column('frequency_unit', sa.Enum('day', 'week', 'month', 'year', name='frequencyunit'), nullable=True),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('weekdays', sa.JSON(), nullable=True),
    sa.Column('end_type', sa.Enum('never', 'until', 'counts', name='endtype'), nullable=True),
    sa.Column('until_date', sa.Date(), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_schedules_amount_positive'),
    sa.CheckConstraint('interval IS NULL OR interval >= 1', name='ck_schedules_interval_positive'),
    sa.CheckConstraint('occurrence_count IS NULL OR occurrence_count >= 1', name='ck_schedules_occurrence_count_positive'),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('histories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('schedule_id', sa.Uuid(), nullable=True),
    sa.Column('medication_id', sa.Uuid(), nullable=True),
    sa.Column('amount_snapshot', sa.Integer(), nullable=False),
    sa.Column('dose_unit_snapshot', sa.Enum('Mg', 'Ml', 'Tablet', 'Capsule', 'Package', 'Drop', name='dosageunit'), nullable=True),
    sa.Column('scheduled_at_snapshot', sa.DateTime(timezone=True), nullable=False),
    sa.Column('intake_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'taken', 'missed', name='historystatus'), nullable=False),
    sa.Column('taken_amount', sa.Integer(), nullable=True),
    sa.Column('memo', sa.String(length=500), nullable=True),
    sa.Column('feeling', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('manual', 'quickCheck', 'system', name='historysource'), nullable=False),
    sa.Column('medication_name_snapshot', sa.String(length=100), nullable=False),
    sa.Column('medication_dosage_form_snapshot', sa.Enum('Tablet', 'Capsule', 'Softgel', 'Liquid', 'Powder', 'Pill', 'Spray', name='dosageform'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount_snapshot > 0', name='ck_histories_amount_snapshot_positive'),
    sa.CheckConstraint('feeling IS NULL OR (feeling >= 1 AND feeling <= 5)', name='ck_histories_feeling_range'),
    sa.CheckConstraint('taken_amount IS NULL OR taken_amount > 0', name='ck_histories_taken_amount_positive'),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('histories')
    op.drop_table('schedules')
    op.drop_table('care_relationships')
    op.drop_table('medications')
    op.drop_index(op.f('ix_care_invitations_invitee_email'), table_name='care_invitations')
    op.drop_table('care_invitations')
    op.drop_table('user_sessions')
    op.drop_table('patients')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
