AVATAR_URL_MAX_LENGTH = 500
AVATAR_URL_MIN_LENGTH = 1

EMAIL_MAX_LENGTH = 255

IP_ADDRESS_MAX_LENGTH = 45

MEDICATION_NAME_MAX_LENGTH = 100
MEDICATION_NAME_MIN_LENGTH = 1
MEDICATION_NOTE_MAX_LENGTH = 500
MEDICATION_NOTE_MIN_LENGTH = 1

NAME_MAX_LENGTH = 100
NAME_MIN_LENGTH = 1

PASSWORD_HASH_MAX_LENGTH = 255
PASSWORD_MAX_LENGTH = 25
PASSWORD_MIN_LENGTH = 10

REFRESH_TOKEN_HASH_MAX_LENGTH = 255

USER_AGENT_MAX_LENGTH = 255
